// @ts-nocheck
import { browser } from 'fumadocs-mdx/runtime/browser';
import type * as Config from '../source.config';

const create = browser<typeof Config, import("fumadocs-mdx/runtime/types").InternalTypeConfig & {
  DocData: {
  }
}>();
const browserCollections = {
  docs: create.doc("docs", {"index.mdx": () => import("../content/docs/index.mdx?collection=docs"), "installation.mdx": () => import("../content/docs/installation.mdx?collection=docs"), "skill.mdx": () => import("../content/docs/skill.mdx?collection=docs"), "core-api/click.mdx": () => import("../content/docs/core-api/click.mdx?collection=docs"), "core-api/cursor.mdx": () => import("../content/docs/core-api/cursor.mdx?collection=docs"), "core-api/destroy.mdx": () => import("../content/docs/core-api/destroy.mdx?collection=docs"), "core-api/do.mdx": () => import("../content/docs/core-api/do.mdx?collection=docs"), "core-api/hover.mdx": () => import("../content/docs/core-api/hover.mdx?collection=docs"), "core-api/if.mdx": () => import("../content/docs/core-api/if.mdx?collection=docs"), "core-api/move.mdx": () => import("../content/docs/core-api/move.mdx?collection=docs"), "core-api/next.mdx": () => import("../content/docs/core-api/next.mdx?collection=docs"), "core-api/pause.mdx": () => import("../content/docs/core-api/pause.mdx?collection=docs"), "core-api/removePlugin.mdx": () => import("../content/docs/core-api/removePlugin.mdx?collection=docs"), "core-api/setState.mdx": () => import("../content/docs/core-api/setState.mdx?collection=docs"), "core-api/stop.mdx": () => import("../content/docs/core-api/stop.mdx?collection=docs"), "core-api/type.mdx": () => import("../content/docs/core-api/type.mdx?collection=docs"), "core-api/until.mdx": () => import("../content/docs/core-api/until.mdx?collection=docs"), "core-api/use.mdx": () => import("../content/docs/core-api/use.mdx?collection=docs"), "core-api/wait.mdx": () => import("../content/docs/core-api/wait.mdx?collection=docs"), "core-api/waitForEvent.mdx": () => import("../content/docs/core-api/waitForEvent.mdx?collection=docs"), "plugins/clicksound.mdx": () => import("../content/docs/plugins/clicksound.mdx?collection=docs"), "plugins/custom-plugins.mdx": () => import("../content/docs/plugins/custom-plugins.mdx?collection=docs"), "plugins/geminitts.mdx": () => import("../content/docs/plugins/geminitts.mdx?collection=docs"), "plugins/indicator.mdx": () => import("../content/docs/plugins/indicator.mdx?collection=docs"), "plugins/logging.mdx": () => import("../content/docs/plugins/logging.mdx?collection=docs"), "plugins/ripple.mdx": () => import("../content/docs/plugins/ripple.mdx?collection=docs"), "plugins/say.mdx": () => import("../content/docs/plugins/say.mdx?collection=docs"), "plugins/speech.mdx": () => import("../content/docs/plugins/speech.mdx?collection=docs"), "plugins/theme.mdx": () => import("../content/docs/plugins/theme.mdx?collection=docs"), "plugins/trail.mdx": () => import("../content/docs/plugins/trail.mdx?collection=docs"), }),
};
export default browserCollections;